### ISSUE TITLE
[Enhancement?] Create 1 game with multiple Platforms, instead of duplicate games of 1 Platform each

### ISSUE THREAD

**Issue by DanDoes** [Jeshibu/Playnite-OculusLibrary#10]
Version: 2.6.1

After initial successful import, I'm seeing duplicates of games with the same info aside from Platform, eg one game with "Oculus Go" and another with "Meta Quest". Preferably these duplicates would be prevented by assigning multiple platforms to each game, as applicable.
(I'm assuming this is a feature request and not a bug)

---

### Example of desired behavior in Playnite:
![image](https://github.com/user-attachments/assets/511df2f3-02c0-4070-a744-65ecf165cb33)

---

### Example of game in Meta app store listing its platforms:
![image](https://github.com/user-attachments/assets/ef1e5472-f115-4db0-9b23-f29269e8db4b)

**Comment by Jeshibu** [comment]
I don't think this is a good idea right now, but I'll take a look at how Playnite 11 does game merging when it comes out.

What the Oculus plugin does is looking at lists like these for each type of system (Rift/Quest/Go): https://secure.oculus.com/my/gear-vr-go/
Each game that is available on both Go and Quest will have two different store entries, and two different IDs. Playnite asks library plugins for a list of games, which it distinguishes by ID. Games are added to the import ignore list via this ID too, which complicates imagining a new ID for games where you have a version for Quest the first time you import and Quest + Go the second time.

If you want the platforms like in your last image, do a metadata import from "Official Store" for already-imported games, and you'll get that. It's a bit of a hacky workaround because I think that having one "Meta Quest" platform is usually preferable.

**Comment by DanDoes** [comment]
AH, I didn't realize Meta kept multiple store entries, apologies. The duplicates make sense now.
That also explains why I couldn't easily find a game in the Meta store that listed the "Go" alongside any "Quest" in its platform list!

(As for having Quest 1/2/3/etc in the Platform list for Quest games, I was already writing a [separate request](https://github.com/Jeshibu/Playnite-OculusLibrary/issues/11) for that 😄)
